name: Deploy to Netlify & Notify Pentest Tools

on:
  push:
    branches:
      - master

jobs:
  deploy-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project (optional)
        run: npm run build

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: |
          netlify deploy \
            --dir=dist \
            --prod \
            --auth=${{ secrets.NETLIFY_TOKEN }} \
            --site=${{ secrets.NETLIFY_SITE_ID }}

      - name: Run Website Scanner on Target
        run: |
          curl --request POST \
            --url http://143.198.6.54:8200/api/v1/vulture/scans/start-ci-cd \
            --header 'accept: application/json' \
            --header 'authorization: ${{ secrets.TOKEN_VULTURE }}' \
            --header 'Content-Type: application/json' \
            --data '{
              "tool_id": 170,
              "target_name": "https://www.hackthissite.org/",
              "tool_params": {
                "scan_type": "deep"
              },
              "description": "Deployed to Netlify",
              "recipient_emails": ["ulilbinabdul@gmail.com"],
              "recipient_whatsapp": ["085718741537"]
            }'
